[connections.mimic_db]
    type="sql"
    dialect="mysql"
    username="mimic"
    password="mimic"
    host="localhost"
    port=3307
    database="mimicdb"


[mysql]
host = "localhost"
database = "mimicdb"
user = "mimic"
password = "mimic"
port = 3307

[openai]
key = "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"